### PR TITLE
Use two args rsa constructor

### PR DESCRIPTION
**Pull request by zapodot**
Use two-args constructor to setup RSAAlgoritm for decoding and verification of JWTs

### CODE REVIEW

**Comment by zapodot** [comment]
Same functional change as #25 minus the .net 4.7.2 dependency as this breaks our non-VisualStudio build environment and pipeline

**Review by IvanILanekassen — APPROVED** [review]
I think this will solve the problem, but need to verify on .NET Framework after a new package is created.

**Comment by zapodot** [comment]
@IvanILanekassen I can push a pre-release version to nuget as soon as I get the chance so you get the chance to test it in your environment

**Comment by IvanILanekassen** [comment]
OK @zapodot, please notify me when it is available and I will do a test.

**Pull request merged**
