### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by runenilsenoe**
Primarily to avoid using vulnerable JWT version

### CODE REVIEW

**Comment by runenilsenoe** [comment]
tired of warnings firing from dep on system.txt.json that has security issues so i updated the JWT project and then i updated your JWT version to that version

**Comment by runenilsenoe** [comment]
@Kolbein any chance to merge?

**Comment by Kolbein** [comment]
@runenilsenoe  Yes, I'll take a look tomorrow! :+1:

**Comment by Kolbein** [comment]
@runenilsenoe Da er en ny release av klienten ute på NuGet :rocket:

**Pull request merged**
